<?php
/** @var \Training\Seller\Block\Seller\View $block */
$seller = $block->getCurrentSeller();
?>
<table>
    <tr>
        <th><?php /* @escapeNotVerified */ echo __("ID") ?></th>
        <td><?php echo $block->escapeHtml($seller->getSellerId()); ?></td>
    </tr>
    <tr>
        <th><?php /* @escapeNotVerified */ echo __("Identifier") ?></th>
        <td><?php echo $block->escapeHtml($seller->getIdentifier()); ?></td>
    </tr>
    <tr>
        <th><?php /* @escapeNotVerified */ echo __("Name") ?></th>
        <td><?php echo $block->escapeHtml($seller->getName()); ?></td>
    </tr>
</table>
<a href="<?php echo $block->getSellersUrl(); ?>"><?php /* @escapeNotVerified */ echo __('Back to the list'); ?></a>
